[package]
name = "number_wall_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
number_wall_generator = { path = "../number_wall_generator" }
json = "*"
image = "*"